Repository WalkerAndCoBrandsInc/tracker, pull requests merged in 2018-07, with the labels that each got.

#3 update handler to take queue_class and client_class
  README.md
  lib/tracker.rb
  lib/tracker/controller.rb
  lib/tracker/middleware.rb
  spec/lib/tracker/controller_spec.rb
  spec/lib/tracker/middleware_spec.rb
Labels: Waiting on Reviewers

#4 fix bug when integration with goatee
  README.md
  lib/tracker/background/sidekiq.rb
  lib/tracker/handlers/ahoy.rb
  lib/tracker/handlers/google_analytics.rb
  spec/lib/tracker/background/sidekiq_spec.rb
  spec/lib/tracker/controller_spec.rb
  spec/lib/tracker/handlers/ahoy_spec.rb
  spec/lib/tracker/handlers/google_analytics_spec.rb
  spec/support/metal_controller.rb
Labels: Merge when build passes

#5 track page as part of middleware
  lib/tracker/handlers/ahoy.rb
  lib/tracker/handlers/base.rb
  lib/tracker/handlers/google_analytics.rb
  lib/tracker/middleware.rb
  lib/tracker/page_track.rb
  spec/lib/tracker/background/sidekiq_spec.rb
  spec/lib/tracker/controller_spec.rb
  spec/lib/tracker/handlers/ahoy_spec.rb
  spec/lib/tracker/handlers/base_spec.rb
  spec/lib/tracker/handlers/google_analytics_spec.rb
  spec/lib/tracker/middleware_spec.rb
  spec/spec_helper.rb
  spec/support/app.rb
  spec/support/env_helpers.rb
  spec/support/metal_controller.rb
  spec/support/uuid_setting.rb
  tracker.gemspec
Labels: Merge when build passes

#6 don't track bot page views; store user agent attrs are sep. keys
  lib/tracker/handlers/base.rb
  lib/tracker/middleware.rb
  spec/lib/tracker/controller_spec.rb
  spec/lib/tracker/handlers/base_spec.rb
  tracker.gemspec
Labels: Merge when build passes

#7 use rack session id instead do ahoy's visitor_id
  README.md
  lib/tracker.rb
  lib/tracker/handlers.rb
  lib/tracker/handlers/ahoy.rb
  lib/tracker/handlers/base.rb
  lib/tracker/handlers/google_analytics.rb
  lib/tracker/middleware.rb
  spec/lib/tracker/controller_spec.rb
  spec/lib/tracker/handlers/base_spec.rb
  spec/spec_helper.rb
Labels: Waiting on Reviewers

#8 use proper keys for sending utm params to GA
  lib/tracker/handlers/google_analytics.rb
Labels: Waiting on Reviewers

#10 do not page track 404 pages
  lib/tracker/background/base.rb
  lib/tracker/background/sidekiq.rb
  lib/tracker/controller.rb
  lib/tracker/middleware.rb
  spec/lib/tracker/controller_spec.rb
  spec/support/app.rb
Labels: Waiting on Reviewers

#11 use httparty to post to amplitude
  lib/tracker/handlers/amplitude.rb
  lib/tracker/handlers/base.rb
  spec/lib/tracker/handlers/amplitude_spec.rb
  spec/spec_helper.rb
  tracker.gemspec
Labels: Merge when build passes

#12 merge default and page args for amplitude
  lib/tracker/handlers/amplitude.rb
Labels: Merge when build passes

#13 transform registration event into amplitude's identify
  lib/tracker.rb
  lib/tracker/handlers/amplitude.rb
  spec/lib/tracker/handlers/amplitude_spec.rb
  spec/spec_helper.rb
  tracker.gemspec
Labels: Waiting on Reviewers

#14 post regular Registration event before doing identify
  lib/tracker/handlers/amplitude.rb
  spec/lib/tracker/handlers/amplitude_spec.rb
Labels: Waiting on Reviewers

#15 allow tracking without controller/rack
  lib/tracker.rb
  lib/tracker/handlers/base.rb
  lib/tracker/handlers/google_analytics.rb
  lib/tracker/middleware.rb
  lib/tracker/without_controller.rb
  spec/lib/tracker/controller_spec.rb
  spec/lib/tracker/handlers/base_spec.rb
  spec/lib/tracker/without_controller_spec.rb
Labels: Waiting on PR author

#16 change to named args in queue_tracker
  lib/tracker/without_controller.rb
  spec/lib/tracker/without_controller_spec.rb
  spec/spec_helper.rb
Labels: Merge when build passes

#18 Conversion event for GA
  .gitignore
  lib/tracker/handlers/ahoy.rb
  lib/tracker/handlers/amplitude.rb
  lib/tracker/handlers/base.rb
  lib/tracker/handlers/google_analytics.rb
  lib/tracker/version.rb
  spec/lib/tracker/handlers/ahoy_spec.rb
  spec/lib/tracker/handlers/amplitude_spec.rb
  spec/lib/tracker/handlers/base_spec.rb
  spec/lib/tracker/handlers/google_analytics_spec.rb
  spec/support/env_helpers.rb
  spec/support/metal_controller.rb
  spec/support/uuid_setting.rb
Labels: Merge when build passes

#17 Remove password from users payload
  .gitignore
  lib/tracker/handlers/base.rb
  spec/lib/tracker/handlers/amplitude_spec.rb
  spec/lib/tracker/handlers/base_spec.rb
  spec/lib/tracker/without_controller_spec.rb
  spec/support/env_helpers.rb
  spec/support/uuid_setting.rb
Labels: Merge when build passes
